subject/urls.py
from django.urls import path

from subject.views import (
    SubjectListView,
    BookListView,
    CreateCourseView,
    UpdateCourseView,
    DeleteCourseView,
    CreateSubjectView,
    UpdateSubjectView,
    DeleteSubjectView,
    CreateBookView,
    UpdateBookView,
    DeleteBookView,
    download,

)

app_name = 'subject'

urlpatterns = [
    path('subject/<int:pk>', SubjectListView.as_view(), name='subject_list'),
    path('book_list/<int:pk>', BookListView.as_view(), name='book_list'),
    path('create_course/', CreateCourseView.as_view(), name='create_course'),
    path('update_course/<int:pk>', UpdateCourseView.as_view(), name='update_course'),
    path('delete_course/<int:pk>', DeleteCourseView.as_view(), name='delete_course'),
    path('create_subject/<int:pk>', CreateSubjectView.as_view(), name='create_subject'),
    path('update_subject/<int:pk>', UpdateSubjectView.as_view(), name='update_subject'),
    path('delete_subject/<int:pk>', DeleteSubjectView.as_view(), name='delete_subject'),
    path('create_book/<int:pk>', CreateBookView.as_view(), name='create_book'),
    path('update_book/<int:pk>', UpdateBookView.as_view(), name='update_book'),
    path('delete_book/<int:pk>', DeleteBookView.as_view(), name='delete_book'),
    path('download_book/<str:generated_name>', download, name='download_book'),
]

subject_book/urls.py
from django.contrib import admin
from django.urls import path, include

from subject_book.home import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name = 'home'),
    path('course/', include('subject.urls')),
    path('auth/', include('authorization.urls')),
]

subject/models.py
from django.contrib.auth.models import User
from django.db import models


class Course(models.Model):
    name = models.CharField(max_length=200)
    created_by = models.ForeignKey(User,on_delete=models.CASCADE)
    def __str__(self):
        return self.name
    class Meta:
        db_table = 'Course'



class Subject(models.Model):
    name = models.CharField(max_length=200, null=False)
    course = models.ForeignKey(Course,on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User,on_delete=models.CASCADE)
    class Meta:
        db_table = 'Subject'
    def __str__(self):
        return self.name

class Book(models.Model):
    name = models.CharField(max_length=200, null=False)
    generated_name = models.CharField(max_length=255)
    author = models.CharField(max_length=200, null=True)
    file = models.FileField(upload_to='upload/')
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    class Meta:
        db_table = 'Book'
    def __str__(self):
        return self.name

subject/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, Http404
from django.shortcuts import render, redirect
from os.path import join as join_path
from os.path import exists as path_exists
from os.path import basename as file_basename
# Create your views here.
from django.views.decorators.http import require_safe
from django.views.generic import (
    TemplateView, CreateView, UpdateView, DeleteView,
)

from subject.models import Subject, Book, Course
from subject_book.settings import MEDIA_ROOT, LOGIN_REDIRECT_URL
from uploads_app.models import Uploads
from uploads_app.utils import write_file, uploads_url


class SubjectListView(TemplateView):

    template_name = 'subject_list.html'

    def get(self, request, *args, **kwargs):
        subjects = Subject.objects.filter(course_id=kwargs['pk']).all()
        course = Course.objects.get(pk=kwargs['pk'])

        return render(request, self.template_name, {'subjects': subjects, 'course': course})


class BookListView(TemplateView):

    template_name = 'book_list.html'

    def get(self, request, *args, **kwargs):
        books = Book.objects.filter(subject_id=kwargs['pk']).all()
        subject = Subject.objects.get(pk=kwargs['pk'])
        return render(request, self.template_name, {'books': books, 'subject': subject})


class CreateCourseView(LoginRequiredMixin,CreateView):
    login_url = 'auth/login/'
    redirect_field_name = "login"
    permission_required = 'course.add_course'

    def get(self, request, *args, **kwargs):
        self.template_name = 'create_course.html'
        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        name = request.POST.get('name')
        course = Course(name=name, created_by=request.user)
        course.save()

        return redirect('/')


class UpdateCourseView(LoginRequiredMixin,UpdateView):
    login_url = LOGIN_REDIRECT_URL
    permission_required = ['course.add_course']


    def get(self, request, *args, **kwargs):
        course = Course.objects.get(pk=kwargs['pk'])
        self.template_name = 'update_course.html'
        return render(request, self.template_name, {'course': course})

    def post(self, request, *args, **kwargs):
        name = request.POST.get('name')
        course = Course.objects.get(pk=kwargs['pk'])
        course.name = name
        course.save()

        return redirect('/')


class DeleteCourseView(LoginRequiredMixin,DeleteView):
    login_url = LOGIN_REDIRECT_URL
    permission_required = ['course.add_course']
    def get(self, request, *args, **kwargs):
        course = Course.objects.get(pk=kwargs['pk'])
        self.template_name = 'delete_course.html'
        return render(request, self.template_name, {'course': course})

    def post(self, request, *args, **kwargs):
        course = Course.objects.get(pk=kwargs['pk'])
        course.delete()

        return redirect('/')


class CreateSubjectView(LoginRequiredMixin,CreateView):
    login_url = LOGIN_REDIRECT_URL
    permission_required = ['subject.add_subject']
    def get(self, request, *args, **kwargs):
        course = Course.objects.get(pk=kwargs['pk'])
        self.template_name = 'create_subject.html'
        return render(request, self.template_name, {'course': course})

    def post(self, request, *args, **kwargs):
        course = Course.objects.get(pk=kwargs['pk'])
        name = request.POST.get('name')
        subject = Subject(name=name, created_by=request.user, course_id=course.id)
        subject.save()

        return redirect('subject:subject_list', course.id)


class UpdateSubjectView(LoginRequiredMixin,UpdateView):
    login_url = LOGIN_REDIRECT_URL
    permission_required = ['subject.add_subject']
    def get(self, request, *args, **kwargs):
        subject = Subject.objects.get(pk=kwargs['pk'])
        course = Course.objects.get(pk=subject.course_id)
        self.template_name = 'update_subject.html'
        return render(request, self.template_name, {'subject': subject, 'course': course})

    def post(self, request, *args, **kwargs):
        name = request.POST.get('name')
        subject = Subject.objects.get(pk=kwargs['pk'])
        subject.name = name
        subject.save()

        return redirect('subject:subject_list', subject.course_id)


class DeleteSubjectView(LoginRequiredMixin,DeleteView):
    login_url = LOGIN_REDIRECT_URL
    permission_required = ['subject.add_subject']
    def get(self, request, *args, **kwargs):
        subject = Subject.objects.get(pk=kwargs['pk'])
        self.template_name = 'delete_subject.html'
        return render(request, self.template_name, {'subject': subject})

    def post(self, request, *args, **kwargs):
        subject = Subject.objects.get(pk=kwargs['pk'])
        _id = subject.course_id
        subject.delete()

        return redirect('subject:subject_list', _id)


class CreateBookView(LoginRequiredMixin,CreateView):
    login_url = LOGIN_REDIRECT_URL
    permission_required = ['book.add_book']
    def get(self, request, *args, **kwargs):
        subject = Subject.objects.get(pk=kwargs['pk'])
        self.template_name = 'create_book.html'
        return render(request, self.template_name, {'subject': subject})

    def post(self, request, *args, **kwargs):
        subject = Subject.objects.get(pk=kwargs['pk'])
        name = request.POST.get('name')
        author_name = request.POST.get('author_name')
        file = request.FILES['file']
        write_file(file)
        book = Book(name=name, created_by=request.user,
                    subject_id=subject.id,
                    author=author_name,
                    file=file, generated_name=uploads_url(file.name))
        book.save()

        return redirect('subject:book_list', subject.id)


class UpdateBookView(LoginRequiredMixin,UpdateView):
    login_url = LOGIN_REDIRECT_URL
    permission_required = ['book.add_book']
    def get(self, request, *args, **kwargs):
        book = Book.objects.get(pk=kwargs['pk'])
        subject = Subject.objects.get(pk=book.subject_id)
        self.template_name = 'update_book.html'
        return render(request, self.template_name, {'book': book, 'subject': subject})

    def post(self, request, *args, **kwargs):
        name = request.POST.get('name')
        author_name = request.POST.get('author_name')
        book = Book.objects.get(pk=kwargs['pk'])

        book.name = name
        book.author = author_name

        book.save()

        return redirect('subject:book_list', book.subject_id)


class DeleteBookView(LoginRequiredMixin,DeleteView):
    login_url = LOGIN_REDIRECT_URL
    permission_required = ['book.add_book']
    def get(self, request, *args, **kwargs):
        book = Book.objects.get(pk=kwargs['pk'])
        self.template_name = 'delete_book.html'
        return render(request, self.template_name, {'book': book})

    def post(self, request, *args, **kwargs):
        book = Book.objects.get(pk=kwargs['pk'])
        _id = book.subject_id
        book.delete()

        return redirect('subject:book_list', _id)

@require_safe
def download(request, generated_name):
    file = Uploads.objects.filter(generated_name=generated_name).first()
    path = join_path(MEDIA_ROOT, 'upload', file.generated_name)
    if path_exists(path):
        with open(path, 'rb') as fh:
            response = HttpResponse(fh.read(), content_type=file.content_type)
            response['Content-Disposition'] = 'inline; filename=' + file_basename(path)
        return response
    raise Http404

subject/templates/book_list.html
{% extends 'basse.html' %}


{% block title %}
    BOOK lists
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-6 offset-3">
                {% if books %}
                    {% for book in books %}
                        <div class="card my-5">
                            <div class="card-body d-flex justify-content-between">
                                <div class="">
                                    <p>{{ book.name }}</p>
                                </div>

                                <div>
                                    {% if perms.subject.add_book or perms.subject.add_course or perms.subject.add_subject %}
                                        <a href="{% url 'subject:update_book' book.id %}" class="btn btn-dark btn-sm"><i class="bi bi-pencil-square"></i></a>
                                        <a href="{% url 'subject:delete_book' book.id %}" class="btn btn-danger btn-sm"><i class="bi bi-trash"></i></a>
                                    {% endif %}
                                    <a download target="_blank"  href="{% url 'subject:download_book' book.generated_name %}" class="btn btn-outline-primary btn-sm"><i class="bi bi-arrow-down"></i></a>
                                </div>

                            </div>

                            <div class="card-footer">
                                <p>Created by : {{ book.created_by.username }}</p>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <h3>No BOOK ...</h3>
                {% endif %}

                <div class="">
                    {% if perms.subject.add_book or perms.subject.add_course or perms.subject.add_subject %}
                        <a href="{% url 'subject:create_book' subject.id %}" class="btn btn-success">Create Book</a>
                    {% endif %}

                    <a href="{% url 'subject:subject_list' subject.course_id %}" class="btn btn-secondary">Back</a>
                </div>
            </div>

        </div>
    </div>
{% endblock %}

subject/templates/create_book.html
{% extends 'basse.html' %}


{% block title %}
    Create Course
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-6 my-3 offset-3">

                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <label for="book_name">Name:</label>
                    <input id="book_name" type="text" name="name" class="form-control shadow-none">
                     <label for="author_name">Author:</label>
                    <input id="author_name" type="text" name="author_name" class="form-control shadow-none">
                     <label for="file">Book File:</label>
                    <input id="file" type="file" name="file" class="form-control shadow-none">

                    <div>
                        <input type="submit" value="Create" class="btn btn-success my-3">
                        <a href="{% url 'subject:book_list' subject.id %}" class="btn btn-secondary">Back</a>
                    </div>

                </form>
            </div>
        </div>
    </div>
{% endblock %}

subject/templates/create_course.html
{% extends 'basse.html' %}


{% block title %}
    Create Course
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-6 my-3 offset-3">

                <form method="post">
                    {% csrf_token %}
                    <label for="name">Name:</label>
                    <input id="name" type="text" name="name" class="form-control shadow-none">

                    <div>
                        <input type="submit" value="Create" class="btn btn-success my-3">
                        <a href="/" class="btn btn-secondary">Back</a>
                    </div>

                </form>
            </div>
        </div>
    </div>
{% endblock %}

subject/templates/create_subject.html
{% extends 'basse.html' %}


{% block title %}
    Create Subject
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-6 my-3 offset-3">

                <form method="post">
                    {% csrf_token %}
                    <label for="name">Name:

                    </label>
                    <input id="name" type="text" name="name" class="form-control shadow-none">

                    <div>
                        <input type="submit" value="Create subject" class="btn btn-success my-3">
                        <a href="{% url 'subject:subject_list' course.id %}" class="btn btn-secondary">Back</a>
                    </div>

                </form>
            </div>
        </div>
    </div>
{% endblock %}

subject/templates/delete_book.html
{% extends 'basse.html' %}


{% block title %}
    Delete book
{% endblock %}


{% block content %}
    <div class="container">
    <div class="row">
        <div class="col-6">
            <p>Are you sure to delete <b>{{ book.name }}</b> ?</p>


            <form method="post">
                {% csrf_token %}
                <a href="{% url 'subject:book_list' book.subject_id %}" class="btn btn-secondary">Back</a>
                <input type="submit" value="Delete" class="btn btn-danger">
            </form>

        </div>
    </div>
    </div>
{% endblock %}

subject/templates/delete_course.html
{% extends 'basse.html' %}


{% block title %}
    Delete course
{% endblock %}


{% block content %}
    <div class="container">
    <div class="row">
        <div class="col-6">
            <p>Are you sure to delete <b>{{ course.name }}</b> ?</p>


            <form method="post">
                {% csrf_token %}
                <a href="/" class="btn btn-secondary">Back</a>
                <input type="submit" value="Delete" class="btn btn-danger">
            </form>

        </div>
    </div>
    </div>
{% endblock %}

subject/templates/delete_subject.html
{% extends 'basse.html' %}


{% block title %}
    Delete course
{% endblock %}


{% block content %}
    <div class="container">
    <div class="row">
        <div class="col-6">
            <p>Are you sure to delete <b>{{ subject.name }}</b> ?</p>
            <form method="post">
                {% csrf_token %}
                <a href="{% url 'subject:subject_list' subject.course_id %}" class="btn btn-secondary">Back</a>
                <input type="submit" value="Delete" class="btn btn-danger">
            </form>

        </div>
    </div>
    </div>
{% endblock %}

subject/templates/subject_list.html
{% extends 'basse.html' %}


{% block title %}
    Subject lists
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-6 offset-3">
                {% if subjects %}
                    {% for subject in subjects %}
                        <div class="card my-5">
                            <div class="card-body d-flex justify-content-between">
                                <div>
                                    <a href="{% url 'subject:book_list' subject.id %}"
                                   class="btn btn-outline-info">{{ subject.name }}</a>
                                </div>

                                <div class="">
                                      {% if perms.book.add_book or perms.course.add_course or perms.subject.add_subject %}
                                    <a href="{% url 'subject:update_subject' subject.id %}" class="btn btn-outline-secondary"><i class="bi bi-pencil-square"></i></a>
                                  <a href="{% url 'subject:delete_subject' subject.id %}" class="btn btn-outline-danger mx-3"><i class="bi bi-trash"></i></a>
                                        {% endif %}
                                </div>

                            </div>

                            <div class="card-footer">
                                <p>Created by : {{ subject.created_by.username }}</p>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <h3>No Subject ...</h3>
                {% endif %}
                <div class="">
                     {% if perms.subject.add_course or perms.subject.add_book or perms.subject.add_subject%}
                    <a href="{% url 'subject:create_subject' course.id %}" class="btn btn-success">Create
                        Subject</a>
                    {% endif %}

                    <a href="/" class="btn btn-secondary">Back</a>
                </div>


            </div>
        </div>
    </div>
{% endblock %}

subject/templates/update_book.html
{% extends 'basse.html' %}


{% block title %}
    Create Course
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-6 my-3 offset-3">

                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <label for="book_name">Name:</label>
                    <input value="{{ book.name }}" id="book_name" type="text" name="name" class="form-control shadow-none">
                     <label for="author_name">Author:</label>
                    <input value="{{ book.author }}"  id="author_name" type="text" name="author_name" class="form-control shadow-none">

                    <div>
                        <input type="submit" value="Update" class="btn btn-success my-3">
                        <a href="{% url 'subject:book_list' subject.id %}" class="btn btn-secondary">Back</a>
                    </div>

                </form>
            </div>
        </div>
    </div>
{% endblock %}

subject/templates/update_course.html
{% extends 'basse.html' %}


{% block title %}
    Create Course
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-6 my-3 offset-3">

                <form method="post">
                    {% csrf_token %}
                    <label for="name">Name:

                    </label>
                    <input id="name" value="{{ course.name }}" type="text" name="name" class="form-control shadow-none">

                    <div>
                        <input type="submit" value="Create" class="btn btn-success my-3">
                    </div>

                </form>
            </div>
        </div>
    </div>
{% endblock %}

subject/templates/update_subject.html
{% extends 'basse.html' %}


{% block title %}
    Create Subject
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-6 my-3 offset-3">

                <form method="post">
                    {% csrf_token %}
                    <label for="name">Name:

                    </label>
                    <input id="name" value="{{ subject.name }}" type="text" name="name" class="form-control shadow-none">

                    <div>
                        <input type="submit" value="update" class="btn btn-success my-3">
                        <a href="{% url 'subject:subject_list' course.id %}" class="btn btn-secondary">Back</a>
                    </div>

                </form>
            </div>
        </div>
    </div>
{% endblock %}