authorization/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from authorization.views import RegisterView,LoginView

app_name = 'auth'
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
]

subject/urls.py
from django.urls import path

from subject.views import (
    SubjectListView,
    BookListView,
    CreateCourseView,
    UpdateCourseView,
    DeleteCourseView,
    CreateSubjectView,
    UpdateSubjectView,
    DeleteSubjectView,
    CreateBookView,
    UpdateBookView,
    DeleteBookView,
    download,

)

app_name = 'subject'

urlpatterns = [
    path('subject/<int:pk>', SubjectListView.as_view(), name='subject_list'),
    path('book_list/<int:pk>', BookListView.as_view(), name='book_list'),
    path('create_course/', CreateCourseView.as_view(), name='create_course'),
    path('update_course/<int:pk>', UpdateCourseView.as_view(), name='update_course'),
    path('delete_course/<int:pk>', DeleteCourseView.as_view(), name='delete_course'),
    path('create_subject/<int:pk>', CreateSubjectView.as_view(), name='create_subject'),
    path('update_subject/<int:pk>', UpdateSubjectView.as_view(), name='update_subject'),
    path('delete_subject/<int:pk>', DeleteSubjectView.as_view(), name='delete_subject'),
    path('create_book/<int:pk>', CreateBookView.as_view(), name='create_book'),
    path('update_book/<int:pk>', UpdateBookView.as_view(), name='update_book'),
    path('delete_book/<int:pk>', DeleteBookView.as_view(), name='delete_book'),
    path('download_book/<str:generated_name>', download, name='download_book'),
]

subject_book/urls.py
from django.contrib import admin
from django.urls import path, include

from subject_book.home import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name = 'home'),
    path('course/', include('subject.urls')),
    path('auth/', include('authorization.urls')),
]

subject/models.py
from django.contrib.auth.models import User
from django.db import models


class Course(models.Model):
    name = models.CharField(max_length=200)
    created_by = models.ForeignKey(User,on_delete=models.CASCADE)
    def __str__(self):
        return self.name
    class Meta:
        db_table = 'Course'



class Subject(models.Model):
    name = models.CharField(max_length=200, null=False)
    course = models.ForeignKey(Course,on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User,on_delete=models.CASCADE)
    class Meta:
        db_table = 'Subject'
    def __str__(self):
        return self.name

class Book(models.Model):
    name = models.CharField(max_length=200, null=False)
    generated_name = models.CharField(max_length=255)
    author = models.CharField(max_length=200, null=True)
    file = models.FileField(upload_to='upload/')
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    class Meta:
        db_table = 'Book'
    def __str__(self):
        return self.name

templates/basse.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">
          <style type="text/css">
              @import url("https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css");
          </style>
    <title>{% block title %}

    {% endblock %}</title>
</head>
<body>

<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Link</a>
                    </li>


                </ul>

            <form class="d-flex mx-5">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>

                <div class="d-flex align-items-center">
                    {% if user.is_authenticated %}
                        <p style="margin-bottom: 0">{{ user.username }}</p>
                        <a class="btn btn-danger btn-sm mx-5" href="{% url 'auth:logout' %}">Logout</a>
                    {% else %}
                    <a class="btn btn-info btn-sm" href="{% url 'auth:login' %}">Login</a>

                    <a class="btn btn-primary mx-4 btn-sm" href="{% url 'auth:register' %}">Register</a>

                    {% endif %}
                </div>


            </div>
        </div>
    </nav>
</header>


<main>
    {% block content %}

    {% endblock %}
</main>

<footer>

</footer>

<script>

    window.onload = (event) => {

        var toastElList = [].slice.call(document.querySelectorAll('.toast'));
        var toastList = toastElList.map(function (toastEl) {
            return new bootstrap.Toast(toastEl)
        });

        for (let i = 0; i < toastList.length; i++) {
            toastList[i].show();
        }
    }
</script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends 'basse.html' %}

{% block title %}
    HOME PAGE
{% endblock %}


{% block content %}

    <div class="container">
        <div class="row">
            {% if user.is_authenticated %}

                <div aria-live="polite" aria-atomic="true" class="position-relative">
                    <div class="toast-container position-absolute top-0 end-0 p-3">

                        <div data-bs-autohide="true" data-bs-delay="5000" class="toast align-items-center text-white bg-primary border-0" role="alert"
                             aria-live="assertive"
                             aria-atomic="true">
                            <div class="d-flex">
                                <div class="toast-body">
                                   Welcome {{ user.username }} !
                                </div>
                                <button type="button" class="btn-close btn-close-white me-2 m-auto"
                                        data-bs-dismiss="toast"
                                        aria-label="Close"></button>
                            </div>
                        </div>


                    </div>
                </div>


            {% endif %}

            <div class="col-6 offset-3">
                {% if courses %}

                    {% for cours in courses %}
                        <div class="mt-3 d-flex justify-content-between">
                            <div>
                                <a href="{% url 'subject:subject_list' cours.id %}"
                                   class="btn mx-3 btn-outline-primary">{{ cours.name }}</a>
                            </div>
                            <div>
                                 {% if perms.subject.add_course %}
                                <a href="{% url 'subject:update_course' cours.id %}" class="btn btn-outline-secondary"><i class="bi bi-pencil-square"></i></a>
                                <a href="{% url 'subject:delete_course' cours.id %}"
                                   class="btn btn-outline-danger mx-3"><i class="bi bi-trash"></i></a>
                                {% endif %}
                            </div>
                        </div>
                    {% endfor %}

                {% else %}
                    <h3>No Courses ...</h3>
                {% endif %}

                <div class="my-5">
                    {% if perms.subject.add_course %}
                        <a href="{% url 'subject:create_course' %}" class="btn btn-info mx-3">Create Course</a>
                    {% endif %}



                </div>
            </div>
        </div>
    </div>

{% endblock %}